import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      colors: {
        "inverse-on-surface": "#f1f1f1",
        "inverse-primary": "#c1c1ff",
        "on-error-container": "#93000a",
        "surface-bright": "#f9f9f9",
        "secondary-container": "#e4e2e1",
        "primary-fixed-dim": "#c1c1ff",
        "error-container": "#ffdad6",
        "on-surface-variant": "#464651",
        "secondary-fixed": "#e4e2e1",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#e4e2e2",
        "secondary": "#5f5e5e",
        "surface-tint": "#5556a5",
        "primary": "#272674",
        "on-surface": "#1a1c1c",
        "on-primary-fixed-variant": "#3d3d8b",
        "surface-variant": "#e2e2e2",
        "surface-container-high": "#e8e8e8",
        "primary-fixed": "#e2dfff",
        "on-secondary-fixed-variant": "#474746",
        "outline-variant": "#c7c5d3",
        "on-primary": "#ffffff",
        "inverse-surface": "#2f3131",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#464747",
        "surface-dim": "#dadada",
        "on-error": "#ffffff",
        "tertiary": "#303131",
        "on-secondary-fixed": "#1b1c1c",
        "on-tertiary-container": "#b6b5b5",
        "on-primary-container": "#aeafff",
        "on-tertiary-fixed": "#1b1c1c",
        "on-primary-fixed": "#0f095f",
        "tertiary-fixed-dim": "#c7c6c6",
        "primary-container": "#3e3e8c",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#c8c6c5",
        "background": "#f9f9f9",
        "tertiary-container": "#474747",
        "surface": "#f9f9f9",
        "surface-container-highest": "#e2e2e2",
        "on-background": "#1a1c1c",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eeeeee",
        "surface-container-low": "#f3f3f3",
        "outline": "#777682",
        "on-secondary-container": "#656464",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        foreground: "hsl(var(--foreground))",
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },

      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [tailwindcssAnimate],
} satisfies Config;
